name: Test and Publish

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: fluent-cache-modules
          NPM_TOKEN: ${{ secrets.GOATLAB_NPM_TOKEN }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Config NPM cache
        run: export NPM_TOKEN=${{ secrets.GOATLAB_NPM_TOKEN }} && npm config set cache ~/.npm && npm config set cache-min 9999999
      - name: Installing Fluent´s Dependencies
        run: export NPM_TOKEN=${{ secrets.GOATLAB_NPM_TOKEN }} && npm install
      - name: Building Fluent
        run: export NPM_TOKEN=${{ secrets.GOATLAB_NPM_TOKEN }} && npm run build
      - name: Testing Fluent
        run: export NPM_TOKEN=${{ secrets.GOATLAB_NPM_TOKEN }} && npm run test
      - name: Publish to NPM
        run: export NPM_TOKEN=${{ secrets.GOATLAB_NPM_TOKEN }} && npm publish
