name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: fluent-cache-modules
          NPM_TOKEN: ${{ secrets.GOATLAB_NPM_TOKEN }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Config npm secret token
        run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
      - name: Config NPM cache
        run: export NPM_TOKEN=${{ secrets.GOATLAB_NPM_TOKEN }} && npm config set cache ~/.npm && npm config set cache-min 9999999
      - name: Installing Fluent´s Dependencies
        run: export NPM_TOKEN=${{ secrets.GOATLAB_NPM_TOKEN }} && npm install
      - name: Write key file
        env:
          AUTH: ${{ secrets.FLUENT_SERVICE_ACCOUNT_BASE64 }}
        run: |
          echo "$AUTH" | base64 --decode > /home/runner/work/fluent/fluent/fluent-service-account.json
      - name: Building Fluent
        run: export NPM_TOKEN=${{ secrets.GOATLAB_NPM_TOKEN }} && npm run build
      - name: Testing Fluent
        run: export NPM_TOKEN=${{ secrets.GOATLAB_NPM_TOKEN }} && npm run test
